version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teller-api
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HTTPS_PORT=443
      - USE_DOCKER_IP=true
      - HOST_IP=10.1.11.179
    volumes:
      - ./certs:/app/certs
      - ./logs:/app/logs
    ports:
      - "10.1.11.179:5000:5000" #http
      - "10.1.11.179:443:443" #https
    networks:
      app-network:
        ipv4_address: 10.1.11.10
    extra_hosts:
      - "host.docker.internal:10.1.11.179"
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.11.0/24
          gateway: 10.1.11.1
