version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teller-api
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HTTPS_PORT=443
      # - HOST=0.0.0.0
      - USE_DOCKER_IP=true
    volumes:
      # - .:/app/backend
      - ./certs:/app/certs
      - ./logs:/app/logs
    ports:
      - "5000:5000" #http
      - "443:443" #https
    networks:
      app-network:
        ipv4_address: 172.20.0.10
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
